name: Actions CI - Next.js version 12 static site export, GitHub Actions Build and Deploy
on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Setup pnpm
      uses: pnpm/action-setup@v3
      with:
        version: '6'

    - name: Install dependencies
      run: pnpm install

    - name: Build
      run: |
        npm run build
        touch out/.nojekyll

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: main
        folder: out
        clean: true
