name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: clean cache
        run: npm cache clean --force

      - name: Clear node_modules
        run: rm -rf node_modules
        
      - name: install
        run: npm install

      - name: yarn_install
        run: yarn install

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: yarn build