name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
    
      - name: Clear node_modules
        run: rm -rf node_modules
        
      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build

      - name: Deploy to hosting platform
        run: |
          # Add your deployment command here
          # Example: Deploy to Netlify
          npx netlify deploy --prod
